blueprint:
  name: Multi-Sensor Occupancy Automation
  description: Automate actions based on multiple Home Protect occupancy sensors.
  domain: automation
  input:
    occupancy_sensors:
      name: Occupancy Sensors
      description: Select one or more occupancy sensors to monitor.
      selector:
        target:
          entity:
            domain: binary_sensor
            device_class: occupancy

    action_occupied:
      name: Action for Occupied State
      description: Action to perform when any sensor detects occupancy.
      default: []
      selector:
        action: {}

    action_unoccupied:
      name: Action for Unoccupied State
      description: Action to perform when all sensors report unoccupied.
      default: []
      selector:
        action: {}

    delay_unoccupied:
      name: Unoccupied Delay
      description: Time to wait after all sensors show unoccupied before running the unoccupied action.
      default: 0
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart

trigger:
  - platform: state
    entity_id: !input occupancy_sensors

variables:
  occupancy_sensors: !input occupancy_sensors
  delay_unoccupied: !input delay_unoccupied

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ expand(occupancy_sensors.entity_id) | selectattr('state', 'eq', 'on') | list | length > 0 }}
        sequence: !input action_occupied
      - conditions:
          - condition: template
            value_template: >
              {{ expand(occupancy_sensors.entity_id) | selectattr('state', 'eq', 'on') | list | length == 0 }}
        sequence:
          - delay:
              seconds: "{{ delay_unoccupied }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ expand(occupancy_sensors.entity_id) | selectattr('state', 'eq', 'on') | list | length == 0 }}
                sequence: !input action_unoccupied